version: '3.8'
services:
  psql_db:
    platform: linux/x86_64
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    container_name: psql_db
    ports:
      - 5432:5432
    # networks:
    #   - nest
    volumes:
      - ./data/db_data/:/data/db_data

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
    ports:
      - 4000:4000
    depends_on:
      - psql_db
    # networks:
    #   - nest
# networks:
#   nest:
#     driver: bridge
